version: '3.4'
services:
  frontend:
      container_name: bunnyshell-material-kit-frontend
      build:
        context: ./frontend
        target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
        args:
          REACT_APP_BASE_API: ${BACKEND_URL-http://material-kit-backend.local.bunnyshell.com:3080}
      volumes:
        - ./frontend:/var/www/frontend:delegated
      ports:
        - "8080:8080"
