version: '3.4'
services:
  frontend:
      container_name: bunnyshell-material-kit-frontend
      build:
        context: ./frontend
        target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
      volumes:
        - ./frontend:/var/www/frontend:delegated
      ports:
        - "8080:3000"
